name: iChan
version: 1.20.9211316+950
publish_to: none
description: Forum reader
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  async: ^2.4.1
  http: ^0.12.1
  dio: ^3.0.9
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  flutter_cache_manager: ^1.4.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.1
  equatable: ^1.2.0
  font_awesome_flutter: ^8.8.0
  flutter_icons: ^1.1.0
  cupertino_toolbar: ^1.0.0
  cupertino_icons: ^0.1.3
  shimmer: ^1.1.0
  video_player: ^0.10.10
  flutter_vlc_player: ^4.0.2
  chewie: ^0.9.10
  flutter_html:
    git: git@github.com:Zchandev/flutter_html.git
  extended_image: ^1.1.1
  path_provider: ^1.6.11
  package_info: ^0.4.0+16
  device_info: ^0.4.2+4
  scrollable_positioned_list: ^0.1.6
  file_picker: ^1.12.0
  mime_type: ^0.3.1
  url_launcher: ^5.4.11
  get_it: ^4.0.2
  simple_animations: ^2.2.1
  video_thumbnail: ^0.2.2
  universal_html: ^1.2.3
  permission_handler: ^5.0.1+1
  flutter_secure_storage: ^3.3.3
  retry: ^3.0.1
  pull_to_refresh: ^1.6.2
  flutter_slidable: ^0.5.4
  cookie_jar: ^1.0.0
  dio_cookie_manager: ^1.0.0
  flutter_inappwebview: ^4.0.0+4
  gallery_saver: ^2.0.1
  image_gallery_saver: ^1.5.0
  youtube_player_flutter: ^7.0.0+7
  flutter_hooks: ^0.13.1
  flutter_image_compress: ^0.7.0
  exif: ^1.0.3
  receive_sharing_intent: ^1.4.1
  flutter_statusbar_manager: ^2.0.0
  easy_localization: ^2.3.3
  flutter:
    sdk: flutter
dev_dependencies:
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0
dependency_overrides:
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.18.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
